language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
notifications:
  email:
    recipients:
    - pliyosan@gmail.com
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-influxdb-metrics-checker.gemspec
deploy:
  provider: rubygems
  api_key:
    secure: "fdhdtlGTRmoViBWRfL/OgO4IJuOlmLkwmBcaf61K6YyinO/6qMgCV/zat+rF8Wm2VppcCAZjacmV1inkrpYa3vB/q7TasDsk4pjniHMUckoCgyrovSpeNCRKpNu4B81GE03zHzwuDlH11AYEfuh0O7hN0/kULOARvXeqnwvLA58KvF7YL4WKRT7iAF8oQ6E39RLQ/RGaFwBxG0IviVg2nzmIAnknfjsAEXVj9+AoaZiqb6mxEJGYPgyhuFvePXfSv0eOIpPd+vId0BFVpL3s57pKZfIKvPwK9mhqZRyEHrELguAOOMFhnCa0qmajoJlrcqp7V26STdyob5FhdvYE7mz7oKtAb+kp44eaR2XW5/RO4XLQZ57Y6l/NwKcKup6Pz1Ef6LZd5C6y7Q+G8LtyXl98ACFEn/BU7sdw3TIorLKadeYimMl1C9sm9CyaoREJuWf8wZv5kgiGQKtp19tO15MQU0t2ow/q1746Dct/JcZ7GBNL3Zm1HQDv27OoynbeLQ/MEJUl1Rq6hZqlvhYynpcPdJj+8ljaDUtA31gSx899gkqL5I0u6rKUlunyHM1JIKqvmxGajghL4spnPcjc2+vHTrkm3JsOOV6Gq23hl4Ph/kQDAbsYHCa3OBshF2cYvrNBgQ9kwkFdIbX/JbcO3iZE3Ucbo0jqX2cJ88VRgHg="
  gem: sensu-plugins-influxdb-metrics-checker
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: pliyosenpai/sensu-plugins-influxdb-metrics-checker
